-- Criacao das tabelas do sistema Raizes do Nordeste
-- Autor: Pedro Marques Mesquita - RU 4710499

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    endereco VARCHAR(255),
    tipo VARCHAR(30),
    ativa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    idade INT,
    aceite_lgpd BOOLEAN NOT NULL DEFAULT FALSE,
    data_aceite_lgpd TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    preco_base NUMERIC(10,2) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    disponivel_junino BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS estoques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES produtos(id),
    unidade_id BIGINT NOT NULL REFERENCES unidades(id),
    quantidade INT NOT NULL DEFAULT 0,
    atualizado_em TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (produto_id, unidade_id)
);

CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    unidade_id BIGINT NOT NULL REFERENCES unidades(id),
    canal_pedido VARCHAR(20) NOT NULL,
    situacao VARCHAR(40) NOT NULL DEFAULT 'AGUARDANDO_PAGAMENTO',
    valor_total NUMERIC(10,2) NOT NULL,
    forma_pagamento VARCHAR(30),
    situacao_pagamento VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
    criado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS itens_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
    produto_id BIGINT NOT NULL REFERENCES produtos(id),
    quantidade INT NOT NULL,
    preco_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL
);

-- Seed minimo para testes
INSERT INTO unidades (nome, cidade, estado, endereco, tipo, ativa)
VALUES ('Unidade Fortaleza Centro', 'Fortaleza', 'CE', 'Rua das Tapiocas, 100', 'PROPRIA', TRUE);

INSERT INTO clientes (nome, email, telefone, idade, aceite_lgpd, data_aceite_lgpd)
VALUES ('Pedro Teste', 'pedro.teste@raizes.com', '85999990001', 25, TRUE, NOW());

INSERT INTO produtos (nome, descricao, preco_base, ativo, disponivel_junino)
VALUES ('Tapioca Nordestina', 'Tapioca recheada com queijo e carne seca', 18.90, TRUE, FALSE),
       ('Caldo de Milho Junino', 'Caldo especial do Sao Joao', 12.50, TRUE, TRUE),
       ('Baiao de Dois', 'Prato tipico nordestino completo', 35.00, TRUE, FALSE);

INSERT INTO estoques (produto_id, unidade_id, quantidade)
VALUES (1, 1, 50),
       (2, 1, 30),
       (3, 1, 20);

INSERT INTO usuarios (nome, email, senha, perfil, ativo)
VALUES ('Admin Raizes', 'admin@raizes.com', '$2b$10$kcCI/.NbBrVcou08pLNik..LoOJr/EceeVpQhzAq9YePeFtzwhQTS', 'ADMIN', TRUE);
-- senha: raizes4710499
